CREATE TABLE Medical.NewPatientsModified_DT (
    CustomerID varchar(63) NULL,
    Store varchar(511) NULL,
    LastName varchar(255) NULL,
    FirstName varchar(255) NULL,
    Gender varchar(63) NULL,
    DateofBirth nvarchar(200) NULL,
    Street1 varchar(511) NULL,
    Street2 varchar(511) NULL,
    City varchar(127) NULL,
    State varchar(63) NULL,
    Zip varchar(63) NULL,
    Phone1 varchar(127) NULL,
    Phone2 varchar(127) NULL,
    Email varchar(127) NULL,
    LeftLoss varchar(63) NULL,
    RightLoss varchar(63) NULL,
    MailStatus varchar(63) NULL,
    CallStatus varchar(63) NULL,
    MaritalStatus varchar(63) NULL,
    HIPAAWaiverSigned varchar(255) NULL,
    RefSource varchar(511) NULL,
    SubRefSource varchar(511) NULL,
    LastHearingAidPurchase date NULL,
    LastHearingTest date NULL,
    LastModified date NULL,
    SycleExportDate date NOT NULL,
    FranchiseOwner varchar(511) NULL
);
