CREATE TABLE Medical.NewPatientsModified_AE (
    CustomerID nvarchar(max) NULL,
    Store nvarchar(max) NULL,
    LastName nvarchar(max) NULL,
    FirstName nvarchar(max) NULL,
    Gender nvarchar(max) NULL,
    DateofBirth nvarchar(max) NULL,
    Street1 nvarchar(max) NULL,
    Street2 nvarchar(max) NULL,
    City nvarchar(max) NULL,
    State nvarchar(max) NULL,
    Zip nvarchar(max) NULL,
    Phone1 nvarchar(max) NULL,
    Phone2 nvarchar(max) NULL,
    Email nvarchar(max) NULL,
    LeftLoss nvarchar(max) NULL,
    RightLoss nvarchar(max) NULL,
    MailStatus nvarchar(max) NULL,
    CallStatus nvarchar(max) NULL,
    MaritalStatus nvarchar(max) NULL,
    HIPAAWaiverSigned nvarchar(max) NULL,
    RefSource nvarchar(max) NULL,
    SubRefSource nvarchar(max) NULL,
    LastHearingAidPurchase nvarchar(max) NULL,
    LastHearingTest nvarchar(max) NULL,
    GoodToImport int NOT NULL,
    ErrorDescription nvarchar(max) NULL,
    LastModified date NULL,
    SycleExportDate nvarchar(100) NOT NULL,
    FranchiseOwner nvarchar(512) NULL
);
