CREATE TABLE Medical.NewPatientsModified_FF (
    CustomerID nvarchar(max) NULL,
    FirstName nvarchar(max) NULL,
    LastName nvarchar(max) NULL,
    Preferred nvarchar(max) NULL,
    Store nvarchar(max) NULL,
    DateofBirth nvarchar(max) NULL,
    [Purchase Date] nvarchar(max) NULL,
    Street1 nvarchar(max) NULL,
    Street2 nvarchar(max) NULL,
    City nvarchar(max) NULL,
    State nvarchar(max) NULL,
    Zip nvarchar(max) NULL,
    Email nvarchar(max) NULL,
    [Area Code] nvarchar(max) NULL,
    Phone nvarchar(max) NULL,
    [Cell Enabled] nvarchar(max) NULL,
    [Cell Area Code] nvarchar(max) NULL,
    [Cell Phone] nvarchar(max) NULL,
    RefSource nvarchar(max) NULL,
    SubRefSource nvarchar(max) NULL,
    [Do Not Mail] nvarchar(max) NULL,
    [Promotion Call] nvarchar(max) NULL,
    CallStatus nvarchar(max) NULL,
    [National Do Not Call] nvarchar(max) NULL,
    [Internal Do Not Call] nvarchar(max) NULL,
    [Do Not Email] nvarchar(max) NULL,
    HIPAAWaiverSigned nvarchar(max) NULL,
    [Insurance Customer] nvarchar(max) NULL,
    [Ins 1 Source] nvarchar(max) NULL,
    [Ins 2 Source] nvarchar(max) NULL,
    [Ins 1 Company] nvarchar(max) NULL,
    [Ins 2 Company] nvarchar(max) NULL,
    [Created On] nvarchar(max) NULL,
    [Created By] nvarchar(max) NULL,
    [Updated On] nvarchar(max) NULL,
    [Updated By] nvarchar(max) NULL,
    FranchiseOwner nvarchar(max) NULL,
    [LastHearingAidPurchase] nvarchar(max) NULL,
    [LastHearingTest] nvarchar(max) NULL,
    GoodToImport int NULL,
    ErrorDescription nvarchar(max) NULL,
    LastModified date NULL,
    SycleExportDate nvarchar(max) NULL
);
